# pull official base image
FROM node:alpine
RUN apk add --update --no-cache gcc g++ make curl py3-pip
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent


# add app
COPY . ./

# start app
CMD ["npm","run","start"]